### ISSUE TITLE
findLocalScopes(node, null) provides all local variables in the scope ignoring node's position

### ISSUE THREAD

**Issue by numberpi** [oracle/graalpython#1]
```python
def myfunc(arg):
    y = 1
    x = 2
```

`findLocalScopes(node, null)` returns always `[arg, y, x]` for a node inside `myfunc(arg)`

See SLLanguage.findLocalScopes() how it should be done collecting only the local variables already defined.

**Comment by eregon** [comment]
Related: https://github.com/oracle/truffleruby/issues/1335
