### ISSUE TITLE
Issue with list comprehension

### ISSUE THREAD

**Issue by oroppas** [oracle/graalpython#101]
Hi,

The simple list comprehension does not seem to work.

```
libs = 'mkl , , openblas, blis, '
print(libs)
print([b for b in [a.strip() for a in libs.split(',')] if b])
```

CPython
```
mkl , , openblas, blis, 
['mkl', 'openblas', 'blis']
```

Graal Python
```
Traceback (most recent call last):
  File "/home/ryutas/graalpython/list_comprehension/test.py", line 3, in <module 'test.py'>
    print([b for b in [a.strip() for a in libs.split(',')] if b])
NameError: name 'a' is not defined
```

Could this be a bug in Graal Python?

**Comment by ppisl** [comment]
Thanks for reporting this. I'm going to fix it. This issue is cased by new parser that was integrated last week. You can use switch --python.UseExperimentalParser=false to use original parser. We are going to keep both parsers for a while.

**Comment by oroppas** [comment]
Hi @ppisl,

Thanks for the info. I'll be waiting for the fix for the new parser. Meanwhile, I tried to revert to the old parser without success:

```
$ graalpython --experimental-options --python.UseExperimentalParser=false ./test.py 
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
mkl , , openblas, blis, 
Traceback (most recent call last):
  File "/run/media/ryutas/fba67dee-3fe6-4f11-980a-3e50e9a564c5/Ryuta_Data/graalpython/list_comprehension/test.py", line 3, in <module 'test.py'>
    print([b for b in [a.strip() for a in libs.split(',')] if b])
NameError: name 'a' is not defined
```

Can you verify this behavior?

**Comment by linl33** [comment]
A similar issue is still present in version 20.3.0. Graal throws a NameError when the nested comprehension is a generator.

```
>>> [e for e in (s.strip() for s in '1 2 3'.split(' '))]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 's' is not defined

>>> [e for e in [s.strip() for s in '1 2 3'.split(' ')]]
['1', '2', '3']
```

CPython
```
>>> [e for e in (s.strip() for s in '1 2 3'.split(' '))]
['1', '2', '3']
```

**Comment by msimacek** [comment]
I can reproduce that, thank you for the report. @ppisl would you mind taking a look?

**Comment by ppisl** [comment]
I am working on this and I have found the problem and fix. Should be propageted here soon.

**Comment by oroppas** [comment]
I can confirm this issue is fixed on my side.

**Comment by ppisl** [comment]
Thanks for verifying this.
