### ISSUE TITLE
graalpython ssl support

### ISSUE THREAD

**Issue by vafaranosov** [oracle/graalpython#127]
Hi experts,
Can you please advise when ssl support is going to be implemented for graalpython?

Kind Regards,
Volodymyr

**Comment by timfel** [comment]
Hi, there is no ETA for this. It's on our nice-to-have list, but no one is actively working on it.

**Comment by johnjelinek** [comment]
Any updates on this? It'd be great to be able to hit HTTPS endpoints with `requests`

**Comment by timfel** [comment]
We have put it on the roadmap, but it's still way down the list and looking to come towards the second half of 2021

**Comment by msimacek** [comment]
SSL support has been added to graalpython in master
