### ISSUE TITLE
Jython Mode - Subclassing

### ISSUE THREAD

**Issue by tbpassin** [oracle/graalpython#129]
In the doc section 

"Subclassing Java Classes and Implementing Interfaces with Python Classes

This is not supported at all right now, there's no emulation available even in Jython compatibility mode. We have not seen many uses of this in the wild. Let us know if this is of interest to you!"

Yes, I'm interested.  Here's a simple example of a servlet:
```
class JythonServlet2 (HttpServlet): 
    def doGet(self,request,response): 
        self.doPost (request,response) 
        
    def doPost(self,request,response): 
        toClient = response.getWriter() 
        response.setContentType ("text/html") 
        toClient.println ('''\
        <html>
            <head><title>Servlet Test 2</title>
            <body><h1>Servlet Test 2</h1></body>
        </html>''') 
```
I would like to be able to write other servlets with Jython, and I have written a few simple ones for personal projects.  I'd also like to write servlet filters in Jython as well.  Jython has a few helper classes to hook these servlets and filters into a servlet system (and there's a bug in the one for filters).

**Comment by shoaniki** [comment]
The 21.1 release notes imply that this is now supported?  The documentation doesn't appear to have been updated with details yet.

**Comment by ppisl** [comment]
We add the basic support. Needs some work, but the basic stuff should work.

**Comment by tbpassin** [comment]
Thanks for working on this!

**Comment by ppisl** [comment]
The basic support is there. I'm closing this issue, please open new one for any problem. Thanks.

**Comment by msimacek** [comment]
Note the usage is sometimes a bit different from Jython. It is documented in https://github.com/oracle/graalpython/blob/master/docs/user/Jython.md#inheritance-from-java
