### ISSUE TITLE
Constantly growing heap

### ISSUE THREAD

**Issue by dkondagit** [oracle/graalpython#151]
Hello.
We are trying to use graalpython to process python scripts in spring boot application.
We tried several options:
1) use new Engine each time;
2) use shared engine;
3) disable source caching via **.cached(false)**

but in each case we see that heap is growing and then application fails - maximum value for memory was 6GB.
Heap grows on each python script processing call. Sometimes we are observing Code Cache warning - CodeCache is full. Compiler has been disabled.

I tried to analyze heapdumps and see that number of following objects is growing:
1) a lot of objects from **com.oracle.graal.python.nodes.frame** package (**ReadLocalVariableNode**, **ReadGlobalOrBuiltinNodeGen**, **ReadVariableFromFrameNodeGen** etc)
2) objects from **com.oracle.graal.python.nodes.attributes** package (**ReadAttributeFromObjectNodeGen$ReadAttributeFromObjectNotTypeNodeGen**, **LookupAttributeInMRONodeGen**)
3) a lot of  **java.lang.ref.WeakReference** objects referencing **com.oracle.graal.python.runtime.AsyncHandler$CallRootNode**
or **com.oracle.graal.python.nodes.function.BuiltinFunctionRootNode**

Python heap is also growing, but values are not terrifying.

Can you somehow comment on growth of this object?
Maybe we should call smth like manual clean up? I've tried to traverse this repository, but was not able to find such option.

**Comment by timfel** [comment]
Indeed, we are currently leaking memory even after the context is closed. There are multiple problems, some of which we know about (like incorrect strong references to user objects in the optimized AST and code). See also #146.

I've run the interactive shell, which does an `import site` in the beginning in a loop with shared contexts in a shared engine, and here's what I found for RSS each time after the REPL was fully loaded:

```
435716
511560 (+75844)
542964 (+31404)
572820 (+29856)
599184 (+26364)
625232 (+26048)
650676 (+25444)
```

We will investigate this.

**Comment by msimacek** [comment]
We have fixed several memory leaks and added testing infrastructure that should help detecting them. I believe this issue can be closed. Feel free to reopen if you still observe problems.
