### ISSUE TITLE
 Will graalpython provide support for windows?

### ISSUE THREAD

**Issue by 6baobao9** [oracle/graalpython#156]
Will graalpython provide support for windows, because I still use windows as the development environment

**Comment by paulvi** [comment]
I bet Linux (Unix) support should get out of EXPERIMENTAL phase before any resources should go for unlimited Windows issues.

**Comment by timfel** [comment]
Basic windows support has landed in master with https://github.com/oracle/graalpython/commit/e64a9da9d12a3b1113c2e70f621db86470d54938. We currently don't support native extensions on Windows, and many of the standard library features are less tested, but basic examples work. We will continue to improve this, but I still cannot give an ETA.

**Comment by mario45211** [comment]
Is there any ready snaphot build with these changes ? I would like to try GraalVM on windows without manual building it from the source

**Comment by thorlaksson** [comment]
Can I use it with WSL or do I need VM or dual-boot?

**Comment by msimacek** [comment]
Yes, you can use WSL

**Comment by 343996019** [comment]
> 

Do you have instructions for how to build graalpython on Windows? 
Thanks!

**Comment by timfel** [comment]
@343996019 You need to build from a Visual Studio command prompt, to have the Windows compiler toolchain on the PATH. Also, try to make sure you're using as short a path as possible for your checkout, the [ninja](https://github.com/ninja-build/ninja) build tool has no support for paths longer than 260 characters in total, and with the nesting of llvm toolchain paths, we can reach that limit very quickly. I personally always build directly in a folder `C:\X`

**Comment by timfel** [comment]
Link to our roadmap issue: https://github.com/oracle/graalpython/issues/321

**Comment by 343996019** [comment]
> @343996019 You need to build from a Visual Studio command prompt, to have the Windows compiler toolchain on the PATH. Also, try to make sure you're using as short a path as possible for your checkout, the [ninja](https://github.com/ninja-build/ninja) build tool has no support for paths longer than 260 characters in total, and with the nesting of llvm toolchain paths, we can reach that limit very quickly. I personally always build directly in a folder `C:\X`

@timfel thanks for your answer! let me try your suggestions.

**Comment by tushanfufu** [comment]
什么时候发布windows版本的python插件呢？

**Comment by tushanfufu** [comment]
@timfel 这个什么时候可以发布
[截图.pdf](https://github.com/oracle/graalpython/files/11271352/default.pdf)

**Comment by msimacek** [comment]
The latest release has basic windows support.
