### ISSUE TITLE
Provide aarch64 builds

### ISSUE THREAD

**Issue by nullterminated** [oracle/graalpython#160]
Creating this ticket as a show of interest in linux-aarch64 builds of graalpython.

**Comment by timfel** [comment]
Thank you for the declaration of interest. There is currently no timeline for this, but we'll take it into consideration.

**Comment by Andrea-Miele** [comment]
Yes pleease add aarch64 builds

**Comment by msimacek** [comment]
Aarch64 builds should be available for the next release. You can get snapshot builds [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases/)
