### ISSUE TITLE
[interop] Some modules have unreadable members

### ISSUE THREAD

**Issue by fniephaus** [oracle/graalpython#171]
I have only looked at two modules so far, `sys` and `os`, but there might be a lot more. It'd be nice to check all modules of the std lib as part of some test.

## Repro session
```
$ polyglot --shell --jvm
GraalVM MultiLanguage Shell 21.0.0-dev
Copyright (c) 2013-2020, Oracle and/or its affiliates
  JavaScript version 21.0.0-dev
  Python version 3.8.5
  Ruby version 2.6.6
ruby> Truffle::Interop.members(Polyglot.eval('python', 'import sys; sys')).include?('make_flags_class')
true
ruby> Truffle::Interop.read_member(Polyglot.eval('python', 'import sys; sys'), 'make_flags_class')
Unknown identifier: make_flags_class (NameError)
        at <ruby> <top (required)>(<internal:core> core/truffle/boot.rb:1:0-91)
        at <ruby> null(Unknown)
ruby> Truffle::Interop.read_member(Polyglot.eval('python', 'import sys; sys'), 'intern')
<builtin-method 'PBuiltinFunction intern at 0x6278371a' of '<module 'sys'>' objects>
ruby> Truffle::Interop.members(Polyglot.eval('python', 'import os; os')).include?('_fscodec')
true
ruby> Truffle::Interop.read_member(Polyglot.eval('python', 'import os; os'), '_fscodec')
Unknown identifier: _fscodec (NameError)
        at <ruby> <top (required)>(resource:/truffleruby/core/truffle/boot.rb:16:15-96)
        at <ruby> null(Unknown)
```

**Comment by fniephaus** [comment]
Turns out I reported a similar issue a while ago: #140.

**Comment by fniephaus** [comment]
Here's a full list of all unreadable members:

#### Unreadable member(s) of #<Python <module 'os' from 'lib-python/3/os.py'>>
- `_fscodec` (*Unknown identifier: _fscodec*)
- `_names` (*Unknown identifier: _names*)
- `_globals` (*Unknown identifier: _globals*)
- `_check_bytes` (*Unknown identifier: _check_bytes*)
- `_have_functions` (*Unknown identifier: _have_functions*)
- `_createenviron` (*Unknown identifier: _createenviron*)
- `_set` (*Unknown identifier: _set*)
- `_add` (*Unknown identifier: _add*)
- `posix` (*Unknown identifier: posix*)

#### Unreadable member(s) of #<Python <module 'sys' (built-in)>>
- `make_flags_class` (*Unknown identifier: make_flags_class*)
- `make_implementation_info` (*Unknown identifier: make_implementation_info*)
- `make_int_info_class` (*Unknown identifier: make_int_info_class*)
- `make_unraisablehook` (*Unknown identifier: make_unraisablehook*)
- `make_hash_info_class` (*Unknown identifier: make_hash_info_class*)
- `make_unraisable_hook_args_class` (*Unknown identifier: make_unraisable_hook_args_class*)
- `make_float_info_class` (*Unknown identifier: make_float_info_class*)
- `make_thread_info_class` (*Unknown identifier: make_thread_info_class*)
- `make_excepthook` (*Unknown identifier: make_excepthook*)

**Comment by timfel** [comment]
Thanks for the list. Our `getMembers` implementation is completely wrong and cannot be trusted. Sorry :) We'll look into it

**Comment by timfel** [comment]
Another simple way to trigger this:
```
>>> class X(): pass
>>> x = X()
>>> x.foo = 1
>>> x.__dict__[object()] = 1
>>> polyglot.__keys__(x)
['foo']
>>> x.__dict__.clear()
>>> polyglot.__keys__(x)
['foo']
>>> x.foo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'X' object has no attribute 'foo'
```
