### ISSUE TITLE
__annotations__ attribute of a function have no "return" key

### ISSUE THREAD

**Issue by kariya-mitsuru** [oracle/graalpython#178]
The sample code below shoud contain "return" key but it contains no "return" key.
```python
def id(arg: int) -> int:
    return arg

print(id.__annotations__)   
```

CPython's output:
```
{'arg': <class 'int'>, 'return': <class 'int'>}
```

GraalPython's output(commit a590fd3d3 & CE 20.3.0):
```
{'arg': <class 'int'>}
```

cf. [Accessing Function Annotations](https://www.python.org/dev/peps/pep-3107/#accessing-function-annotations)

**Comment by timfel** [comment]
Thank you for the report! We will look into it

**Comment by ppisl** [comment]
Working on this now.

**Comment by msimacek** [comment]
I belive this problem has been fixed
