### ISSUE TITLE
Quickstart example that combines Python and Java code

### ISSUE THREAD

**Issue by ge0ffrey** [oracle/graalpython#182]
Graalpython seems like an excellent way to expose many of the libraries in the Java ecosystem to Python users.
However, getting started with it - and combining Python and Java code - is tricky.
A good quickstart repo would really enable more people to pick this up.

**Comment by timfel** [comment]
Do you mean something like what we have on the website, just as a repository? https://www.graalvm.org/reference-manual/embed-languages/

**Comment by ge0ffrey** [comment]
Yes, something that we can check out and build. Something that immediately builds:
- because we didn't make a mistake when copy-pasting from the that website tutorial
- and neither because the website tutorial contains a bug (which I am sure it never does ;-) )

Reason I ask: I am investigating if it's possible to create a python implementation of OptaPlanner's school-timetabling example.
There is already have one for Java and Kotlin: https://github.com/kiegroup/optaplanner-quickstarts

**Comment by timfel** [comment]
We have something to that effect now: https://github.com/hpi-swa-lab/graalpython-java-example/
