### ISSUE TITLE
Using java libraries in GraalPython

### ISSUE THREAD

**Issue by schefflaa** [oracle/graalpython#185]
Hey there. Is it possible to use java libraries via Maven (or otherwise) with (Graal-) Python as the base language?

To be more precise, we'd like to use the [jpmml-evaluator library](https://github.com/jpmml/jpmml-evaluator) in GraalPython. Now we know that there is a [Python wrapper](https://github.com/jpmml/jpmml-evaluator-python) of this library but this is not the case for every java library.

From what we've understood it is perfectly possible to run java code and native java libraries (e. g. import java.util.*) but does this not include the use of other libraries?

**Comment by timfel** [comment]
There is no special integration with maven, but anything you put on the classpath can be used from GraalPython. So yes, you can use arbitrary Java libraries from Python.

**Comment by schefflaa** [comment]
That's great, thank you very much! Could you point me to some reading material? Haven't found anything regarding this on the [graal vm website](https://www.graalvm.org/docs/introduction/)..

**Comment by timfel** [comment]
There isn't really anything. If you use the graalpython launcher, you can type
```
graalpython --jvm --help:vm
```
This will give you (among other things) this argument:
```
--vm.classpath=<path>[:path...]              Manage the classpath for Java libraries that you can access from guest languages (':' separated list)
```

So you just need to find out what the classpath is for your additional libraries, and run something like this for a hypthetical application Jar:
```
$ graalpython --jvm --vm.classpath=contoso.jar
Python 3.8.5 (Tue Jan 19 09:17:50 CET 2021)
[Graal, Interpreted, Java 1.8.0_251] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import java
>>> maincl = java.type("com.contoso.app.Main")
>>> maincl.main([])
```

**Comment by schefflaa** [comment]
Please forgive my ignorance, but I have a genuinely hard time figuring out how translate a few lines of java code into GraalPython.

So using JARs in GP works basically the same way one would use JAR-files in java; except its `--vm.classpath=` instead of `-cp`. I think I got that. But as soon as I try to apply your hypothetical example to my use case I run into some issues.

This is the (first) [part of the code](https://github.com/jpmml/jpmml-evaluator#basic-usage) I am trying to migrate:
`
Evaluator evaluator = new LoadingModelEvaluatorBuilder()
                .load(new File("/home/.../file.pmml"))
                .build();
`

![Here's what I am looking at in the debugger after importing the .jar](https://user-images.githubusercontent.com/37218130/105364684-be26cf00-5bfd-11eb-97e1-780dede4337b.png).

I feel like I am missing some basic information on how to transform java code into graalpython.

**Comment by timfel** [comment]
This Java code:
```java
Evaluator evaluator = new LoadingModelEvaluatorBuilder()
    .load(new File("/home/.../file.pmml"))
    .build();
```

would be this in GraalPython:
```python
LoadingModelEvaluatorBuilder = java.type("org.jpmml.evaluator.LoadingModelEvaluatorBuilder")
File = java.type("java.io.File")

evaluator = LoadingModelEvaluatorBuilder().load(File("/home/.../file.pmml")).build()
```

**Comment by timfel** [comment]
Btw, I'm not sure what you want to show with the screenshot - it looks perfectly fine.

**Comment by schefflaa** [comment]
Alright, so this does make things definitely clearer. Thanks again for your support, I gladly appreciate it. I think the biggest realisation I made was the necessity to add another parentheses after the `java.type()` method; in retrospect this seems trivial.

Regarding my screenshot: I just wanted something to provide to you so you could better understand where I am stuck.
