### ISSUE TITLE
How to access PyDictionary from embedded Python in Java?

### ISSUE THREAD

**Issue by fra-orolo** [oracle/graalpython#187]
We have some Java API methods accepting key-value maps as method parameters. 
These should be used in embedded Python scripts.

```java
public void setOptions(Map<String, Object>) {
   //...
}
```
This should ideally be called in embedded Python as
```python
setOptions({'a': 1, 'b': True})
```
We tried to implement this API as direct call or using ProxyExecutable.

If the Python dictionary arrives as Value in Java, it can be mapped with dictValue.as(HashMap.class) but that creates a Map of member-methods. 
It is possible to call ```Value dictKeys = dictValue.getMember("keys").execute()``` this results in a view on the python keyset, but that does not expose anything useful for iteration in Java. 
We found two hacky ways to convert: either by calling back to python and create the Java converted object there or to access the hidden member methods `iter=__iter__() and iter.__next__()` on the keyset. (see attached test class).

Wouldn't it be great if the host language could use something like `value.as(Set.class)` to allow iteration on builtin Python types?
Or did I miss something else. In Jython this used to be very easy.

[PythonGraalIssuesTest.java.txt](https://github.com/oracle/graalpython/files/5874191/PythonGraalIssuesTest.java.txt)

**Comment by timfel** [comment]
Iteration over `Value` objects is being worked on and likely to arrive in the next release.

**Comment by fra-orolo** [comment]
Great! Then let's close this.
