### ISSUE TITLE
Spurious ValueError

### ISSUE THREAD

**Issue by oroppas** [oracle/graalpython#188]
GraalPython gives `ValueError: '_path' in __slots__ conflicts with class variable` for the following code:

```python
from typing import Optional
from pathlib import Path

class Style:

    _path: Optional[Path]

    __slots__ = [
        "_path"
    ]


if __name__ == '__main__':
    Style()
```

CPython gives no error.

**Comment by ppisl** [comment]
Hello @oroppas, thank for the report. It looks that problem is that graalpython translate line
```_path: Option[Path]``` to somothing like
```_path: {type of Option[Path]} = None``` and createss `_path` variable in the class body. I will try to fix it. 

Why you have here the line with ```_path: Optional[Path]```

**Comment by oroppas** [comment]
Hi @ppisl,

It's been a while since I submitted this bug report and my memory is a bit rusty
but I think I found it when I tried rich (https://github.com/willmcgugan/rich).
https://github.com/willmcgugan/rich/blob/master/rich/style.py#L63

**Comment by ppisl** [comment]
@oroppas Thanks for the response. The problem is clear to me. I'm working on it.

**Comment by oroppas** [comment]
@ppisl I can confirm the fix works. Thanks!

**Comment by ppisl** [comment]
> @ppisl I can confirm the fix works. Thanks!

You are welcome and thanks for chacking it.
