### ISSUE TITLE
Unable to import interpolate from scipy library (GraalVM Community 20.3.0)

### ISSUE THREAD

**Issue by matesu** [oracle/graalpython#194]
Hello,
I wanted to test scipy library on GraalVM inside Docker (testing on Windows) and I couldn't to do so.

My setup is as follows:
* Docker image based on  latest Ubuntu
* GraalVM version: graalvm-ce-java8-linux-amd64-20.3.0
* additional utilities installed: curl tar unzip patch gcc gfortran python3-dev libopenblas-dev liblapack-dev cython

Dockerfile looks like this:
```Dockerfile
FROM ubuntu
ENV GRAAL_VERSION 20.3.0
ENV GRAAL_PKG graalvm-ce-java8-linux-amd64-$GRAAL_VERSION
WORKDIR /app
RUN apt update -y && apt install -y curl tar unzip patch gcc gfortran python3-dev libopenblas-dev liblapack-dev cython
RUN curl -L -o /app/$GRAAL_PKG.tar.gz https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-$GRAAL_VERSION/$GRAAL_PKG.tar.gz \
  && tar xfvz $GRAAL_PKG.tar.gz

ENV JAVA_HOME=/app/graalvm-ce-java8-$GRAAL_VERSION \
    PATH=$PATH:/app/graalvm-ce-java8-$GRAAL_VERSION/bin
RUN ln -s /app/graalvm-ce-java8-$GRAAL_VERSION/bin/java /usr/bin/java

RUN gu install python
RUN graalpython -m venv graal_venv
SHELL ["/bin/bash", "-c"]
RUN source graal_venv/bin/activate && graalpython -m ginstall install scipy && graalpython -m ginstall install pandas
```

After building that image I run it and tried to import `interpolate` from `scipy` but got an error:

```bash
root@665051b74f9a:/app# source graal_venv/bin/activate
(graal_venv) root@665051b74f9a:/app# graalpython
Python 3.8.5 (Thu Nov 12 21:59:05 UTC 2020)
[Graal, GraalVM CE, Java 1.8.0_272] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from scipy import interpolate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot load /app/graal_venv/lib/python3.8/site-packages/scipy-1.3.1-py3.8-linux-x86_64.egg/scipy/special/_ufuncs.graalpython-38-native-x86_64-linux.so: LoadNativeNode is called with unexpected arguments
```

I've checked various versions of GraalVM prior to `20.3.0` and the effect was similar. I've even checked latest version (`21.0.0`), but got another error while building an image (same Dockerfile, only GraalVM was changed to `21.0.0`):

```bash
1 warning generated.
/usr/bin/gfortran -Wall -g -fPIC build/temp.linux-x86_64-3.8/build/src.linux-x86_64-3.8/scipy/fftpack/_fftpackmodule.o build/temp.linux-x86_64-3.8/scipy/fftpack/src/zfft.o build/temp.linux-x86_64-3.8/scipy/fftpack/src/drfft.o build/temp.linux-x86_64-3.8/scipy/fftpack/src/zrfft.o build/temp.linux-x86_64-3.8/scipy/fftpack/src/zfftnd.o build/temp.linux-x86_64-3.8/build/src.linux-x86_64-3.8/scipy/fftpack/src/dct.o build/temp.linux-x86_64-3.8/build/src.linux-x86_64-3.8/scipy/fftpack/src/dst.o build/temp.linux-x86_64-3.8/build/src.linux-x86_64-3.8/build/src.linux-x86_64-3.8/scipy/fftpack/fortranobject.o -L/usr/lib/gcc/x86_64-linux-gnu/9 -L/usr/lib/gcc/x86_64-linux-gnu/9 -Lbuild/temp.linux-x86_64-3.8 -ldfftpack -lfftpack -lgfortran -o build/lib.linux-x86_64-3.8/scipy/fftpack/_fftpack.graalpython-38-native-x86_64-linux.so
ld: error: undefined symbol: main
>>> referenced by /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o:(_start)
collect2: error: ld returned 1 exit status
error: Command "/usr/bin/gfortran -Wall -g -fPIC build/temp.linux-x86_64-3.8/build/src.linux-x86_64-3.8/scipy/fftpack/_fftpackmodule.o build/temp.linux-x86_64-3.8/scipy/fftpack/src/zfft.o build/temp.linux-x86_64-3.8/scipy/fftpack/src/drfft.o build/temp.linux-x86_64-3.8/scipy/fftpack/src/zrfft.o build/temp.linux-x86_64-3.8/scipy/fftpack/src/zfftnd.o build/temp.linux-x86_64-3.8/build/src.linux-x86_64-3.8/scipy/fftpack/src/dct.o build/temp.linux-x86_64-3.8/build/src.linux-x86_64-3.8/scipy/fftpack/src/dst.o build/temp.linux-x86_64-3.8/build/src.linux-x86_64-3.8/build/src.linux-x86_64-3.8/scipy/fftpack/fortranobject.o -L/usr/lib/gcc/x86_64-linux-gnu/9 -L/usr/lib/gcc/x86_64-linux-gnu/9 -Lbuild/temp.linux-x86_64-3.8 -ldfftpack -lfftpack -lgfortran -o build/lib.linux-x86_64-3.8/scipy/fftpack/_fftpack.graalpython-38-native-x86_64-linux.so" failed with exit status 1
```
Am I doing something wrong or `scipy` is just not ready to be used? Pandas and numpy are working fine. 

PS Thanks for great project, we use GraalVM extensively with JS and wanted to make first steps with Python

**Comment by timfel** [comment]
Hello, and thanks for asking about scipy. You are right, scipy is not ready to be used.

The reason why we have it enabled at all inside `ginstall` is that the pure Python parts of scipy do work, and those are used in part by packages like scikit-learn. However, almost anything in scipy that uses native extensions also uses Fortran code. On GraalVM, we do not execute C extensions natively, we compile them to bytecode and interpret them on the GraalVM LLVM runtime. Unfortunately, as of right now there is no functional Fortran compiler for LLVM, and thus we cannot currently run scipy and other packages that use Fortran code.

**Comment by matesu** [comment]
Thanks, good to know.

Do you have any ETA regarding packages that use Fortran code, especially scipy? We need to make a few decisions in our project soon, and information about when it will be ready or just it won't for example in at least 2 years, would be very helpful.

**Comment by timfel** [comment]
We are a little dependent on how fast the LLVM flang project will move in that regard. Thus, I really cannot give you an ETA, but it will likely not happen this year.

**Comment by matesu** [comment]
Not an ETA but still something. Thank you and good luck!

**Comment by egorklimov** [comment]
Hello!
Could you, please, add a few notes to the readme that scipy cannot be installed at this time. I understand that this is an experimental interpreter, but this notes will save time for people trying to use graalpython in their ml workflow ;)
As for me, after reading the readme, I thought that maybe some scipy functions might not work correctly, but not the whole scipy.

**Comment by timfel** [comment]
@egorklimov we will make this clearer, but some parts of scipy do work - we have been able to use lightfm and scikit-learn both of which use a few bits from scipy that happen to work :)
