### ISSUE TITLE
false positive detect of user filesystem

### ISSUE THREAD

**Issue by SchrodingerZhu** [oracle/graalpython#197]
```
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a string in the image heap that contains a user directory. This means that file system information from the native image build is persisted and available at image runtime, which is most likely an error.
String that is problematic: http://apache.org/xml/properties/validation/schema/root-type-definition
```

I think it is funny to treat `/root-type-definition` as `/root` especially the when it is in a web url.

**Comment by msimacek** [comment]
Hi @SchrodingerZhu. Graalpython is not doing these checks, it's the native-image feature of GraalVM. Could you please report the issue at https://github.com/oracle/graal?

**Comment by SchrodingerZhu** [comment]
yeah. perhaps that is better. but this problem is stopping me rebuilding python native image (EE).

**Comment by msimacek** [comment]
I understand that, but we cannot fix it in graalpython, it has to be fixed in native-image tool. I filled the issue for you there: https://github.com/oracle/graal/issues/3244. Let's continue there
