### ISSUE TITLE
Exception in thread "main" ModuleNotFoundError: No module named 'sklearn'

### ISSUE THREAD

**Issue by ebremer** [oracle/graalpython#199]
Trying to run this python:
import site;
from sklearn.datasets import load_iris;
from sklearn import tree;
X, y = load_iris(return_X_y=True);
clf = tree.DecisionTreeClassifier();
clf = clf.fit(X, y);
tree.plot_tree(clf);

from java using this:
        File file = new File("test2.py");
        Source source = Source.newBuilder("python", file).build();
        Context context = Context.newBuilder("python")
                .allowIO(true)
                .allowPolyglotAccess(PolyglotAccess.ALL)
                .allowNativeAccess(true)
                .build();
        context.eval(source);

Yields this error:
Exception in thread "main" ModuleNotFoundError: No module named 'sklearn'
        at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:347)
        at com.ebremer.experiments.NewClass.main(NewClass.java:25)

NOTE - scilearn is installed and the above python script works from with python3 test2.py

**Comment by ebremer** [comment]
sklearn is installed and it runs fine using my ubuntu 20 python3 using:
/home/erich/anaconda3/bin/python3
Is this the proper way to define the context with the python.Executable?

        Context context = Context.newBuilder("python")
                .allowIO(true)
                .allowPolyglotAccess(PolyglotAccess.ALL)
                .allowNativeAccess(true)
                .allowAllAccess(true)
                .out(System.out)
                .option("python.Executable", "/home/erich/anaconda3/bin/python3")
                .build();

**Comment by timfel** [comment]
No, you cannot use sklearn installed using any python. You have to use graalpython itself to create a new venv and install sklearn in that.

**Comment by timfel** [comment]
Graalpython is not compatible with packages installed using any other python or another package management system. We need to install packages through graalpython itself.

**Comment by ebremer** [comment]
So, is it impossible to call, from java,  a python script that needs to import other python libraries like scilearn?

**Comment by timfel** [comment]
> So, is it impossible to call, from java, a python script that needs to import other python libraries like scilearn?

No, it is possible. But you need to install these libraries using Graalpython.

Graalpython is a completely new and separate implementation of Python. While it runs the same programs as your system Python, it is not the same thing. It's just like as if you were installing a different version CPython into a different path on your system - it's completely separate.

**Comment by ebremer** [comment]
Understood.  Thank you!  I will try it out.
