### ISSUE TITLE
Wrong __annotations__ 

### ISSUE THREAD

**Issue by oroppas** [oracle/graalpython#206]
Function annotation

```python
def annotated(a: int) -> float:
    pass

print(annotated.__annotations__)
```

in GraalPython misses `return`.

**GraalPython**

```
{'a': <class 'int'>}
```

**CPython**

```
{'a': <class 'int'>, 'return': <class 'float'>}
```

**Comment by ppisl** [comment]
This is the same issue as issue #178 . Because I have pull request that refers the issue #178, I'm closing this as duplicate of the mentioned issue.
