### ISSUE TITLE
import Flask fails

### ISSUE THREAD

**Issue by jsight** [oracle/graalpython#218]
It looks like it has an AST dependency:

```
graalpython 
Python 3.8.5 (Fri Apr 16 11:46:53 UTC 2021)
[Graal, GraalVM CE, Java 11.0.11] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Flask
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'Flask'
>>> from flask import Flask
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jsightler/project/integration/scratch/graal/python/lib/python3.8/site-packages/werkzeug/routing.py", line 550, in <module '/tmp/pip-unpacked-wheel-wyff96r0/werkzeug/routing.py'>
    _IF_KWARGS_URL_ENCODE_AST = _prefix_names(_IF_KWARGS_URL_ENCODE_CODE)
  File "/home/jsightler/project/integration/scratch/graal/python/lib/python3.8/site-packages/werkzeug/routing.py", line 533, in _prefix_names
    tree = ast.parse(src).body[0]
AttributeError: 'code' object has no attribute 'body'
>>> 

```

**Comment by msimacek** [comment]
Thank you for trying graalpython. We're aware that the `ast` module is not working. Unfortunately, it is tied very closely to CPython's parser internals, so it's going to be very hard to support it properly. We will have to support it eventually, but we don't plan to work on it in the near future.
Flask depends on other things that are currently missing - for instance, our sockets support is currently being worked on. Maybe we will be able to patch `werkzeug` to avoid the code-path that is using `ast` after all, but we have to take care of the other prerequisites first.

**Comment by msimacek** [comment]
Just to provide an update - we have implemented the `ast` module and we're now actively working on Flask

**Comment by msimacek** [comment]
The current release (22.3) should now support Flask
