### ISSUE TITLE
[interop] `in` operator does not work for interop string

### ISSUE THREAD

**Issue by fniephaus** [oracle/graalpython#223]
Title says it all :)

#### Repro
```js
$ polyglot --jvm --shell
GraalVM MultiLanguage Shell 21.1.0
Copyright (c) 2013-2020, Oracle and/or its affiliates
  JavaScript version 21.1.0
  Python version 3.8.5
  Ruby version 2.7.2
  Squeak/Smalltalk version 21.2.0-dev
python> import polyglot
python> 'foo' in polyglot.eval(language='ruby', string='"foobar"')
False
python> polyglot.eval(language='ruby', string='"foobar"')
'foobar'
python> 'foo' in str(polyglot.eval(language='ruby', string='"foobar"'))
True
```

**Comment by lukasstadler** [comment]
This should definitely work, but it's an interesting case.
It's a bit more tricky than it looks at first, since "in" works for both string search and array element search.
@eregon  - out of curiosity, what does a Ruby string look like at the interop level? I assume it's both an array and a string?

**Comment by eregon** [comment]
Ruby Strings implement `isString`/`asString`, but not `hasArrayElements`.
It's the same for the default exports of `java.lang.String`.
