### ISSUE TITLE
link to docs in release notes is a 404

### ISSUE THREAD

**Issue by erickj** [oracle/graalpython#224]
The release notes point to http://www.graalvm.org/docs/reference-manual/python/ for more information, but that is a 404. I believe the correct URL is: https://www.graalvm.org/reference-manual/python/

**Comment by msimacek** [comment]
Thank you for the report. I updated the last release manually for now. We'll try to fix the process for future releases. CC @olyagpl @ezzarghili

**Comment by olyagpl** [comment]
@erickj, the link should be working now. Thanks for spotting!
