### ISSUE TITLE
No build for Java 16

### ISSUE THREAD

**Issue by tsturzl** [oracle/graalpython#227]
Hey there! This is a very cool project. I'm doing to experimental work using python as a transform function in a Java code base that uses Java 14+. Graal currently supports Java 16 as experimental, and that's the minimal version I'm able to use with my codebase currently. I see that for graalpython there aren't any builds for Java 16. I'm wondering if you plan to make builds for Java 16 available via `gu` anytime in the near future, or if I'd be stuck compiling this myself for the time being. As far as I can tell graalpython is one of the only languages I see missing for Java 16 builds of graalvm, is there any reason why graalpython may not be working as expected for Java 16 or have you just not created builds for experimental builds of graal?

**Comment by msimacek** [comment]
Hi, thank you for your interest in graalpython. There had been some technical issues in including graalpython on Java 16, but they have been resolved. You can expect a Java 16 build in the next release (21.2.0), which is coming on 20th July (in 5 days).
