### ISSUE TITLE
A few possible docs/changelog mismatches

### ISSUE THREAD

**Issue by mikehearn** [oracle/graalpython#235]
1. The changelog now mentions the POSIX API in the launcher twice. In commit 06a2b927e51c52a7bbe8da8a6611dc9096bca297 the author didn't notice that it was already mentioned on line 23.
2. The changelog mentions that subclassing in Java is now supported, but the Jython compatibility docs still claim it's not.
3. The changelog mentions that hashes/dicts are now support in interop, but the Jython compatibility docs claim there's no mapping of dicts to any other protocol. 
4. Ditto for iteration - changelog  says it's been added, Jython docs say it's not.
4. The changelog says many things have been implemented and failing tests now pass, but the MISSING.md file is a year out of date, which makes it hard to understand how much is actually still missing.

**Comment by msimacek** [comment]
Thank you for the report. I'll try to fix the issues.

**Comment by msimacek** [comment]
Fixed by e77dde25b1612206486b52143448b23d09999c84
