### ISSUE TITLE
ElementTree doesn't work

### ISSUE THREAD

**Issue by pekkaklarck** [oracle/graalpython#243]
I was testing [Robot Framework](http://robotframework.org) on GraalPython and after commenting out `signal` module imports (not mandatory) I got some tests run but generating logs and reports failed because parsing our output.xml file failed. We use ElementTree for parsing XML and sure enough it doesn't work:

```python
>>> from xml.etree import ElementTree as ET
>>> ET.XML('<root/>')
...
NotImplementedError: XML pyexpat parser is not implemented
```

Do you have any plans for adding ElementTree support in the foreseeable future? We are currently dropping Python 2 support which also drops support for Jython. GraalPython looks like a good alternative when needing to work on JVM, but ElementTree not working is a showstopper for us.

**Comment by timfel** [comment]
Hi, and thanks for the question. Given the current state of GraalPython, there are a lot of things to focus on, and reports like yours help us prioritize. So if you need xml support, that is definitely something we'll look into.

**Comment by pekkaklarck** [comment]
That sounds great!! As I wrote, ElementTree not working is a showstopper for us, but based an a quick test it ought to otherwise be possible to get Robot Framework running on GraalPython. We have extensive test suite that we can use to verify that and we'd naturally report possible problems here.

**Comment by msimacek** [comment]
@pekkaklarck Hi, we have added the `pyexpat` module in master. Let us know how it works for you.

**Comment by timfel** [comment]
We're also very interested to hear about anything else that might prevent running Robot Framework on GraalPython, so please let us know if there is anything we can do to help.

**Comment by pekkaklarck** [comment]
Awesome! So you have instructions somewhere how to tester what's on master? Can I install it directly somehow or do I need to clone the repo?

**Comment by timfel** [comment]
We have a builder to regularly push dev builds here: https://github.com/graalvm/graalvm-ce-dev-builds/releases - however, we just noticed that there's been a hiccup pushing out new releases, I'll let you know once a new build has been pushed

**Comment by timfel** [comment]
The error with nightly releases should be fixed, and we have a new set of binaries currently going through the pipeline. They'll appear here: https://github.com/graalvm/graalvm-ce-dev-builds/releases

You'll need to download the graalvm, llvm-toolchain-installable, and python-installable all for the same jdk and platform. In the graalvm, you install first the llvm-toolchain and then python using `gu -L path/to/installable/jar`
