### ISSUE TITLE
toString() to act as __str__()

### ISSUE THREAD

**Issue by cyraid** [oracle/graalpython#245]
```java
public class MyClass {
  private final String str;
  public MyClass(String str) {
    this.str = str;
  }
  @Override
  public String toString() {
    return str;
  }
}
```

I would expect calling:

```java
context.getPolyglotBindings().putMember("obj", new MyClass("HI"));
context.eval("python",
  """
  import polyglot
  obj = polyglot.import_value("obj")
  print(obj)
  """);
```

That it would print "HI" and not <JavaObject[MyClass] at 0xdeadbeef>

Is there a way to make it print it as a string? I've tried using Python's str().

**Comment by msimacek** [comment]
You can always call Java methods using normal Python method calls, so `obj.toString()` should work. You're right that it would make more sense if the string conversion (`__str__` special method) would call `toString()`, I'll try to change it.

**Comment by cyraid** [comment]
@msimacek Thank you very much! It is a requirement for my company. Do you have an ETA for change? :)

**Comment by cyraid** [comment]
@msimacek While you're at it, you could you add .equals() when you compare it with something? Like `myCustomObj.equals("HI")` when `my_custom_obj == "HI"` as well?

**Comment by msimacek** [comment]
It should get merged today. There should be a [nightly build](https://github.com/graalvm/graalvm-ce-dev-builds/releases/) available tomorrow.

As for `equals`, we'll discuss it internally, it could have other consequences.

**Comment by cyraid** [comment]
@msimacek thank you! That was quick! :) I'm off till Monday so I'll see if I can check it then. :) Hope you have a good weekend!

**Comment by msimacek** [comment]
Sorry, it failed to merge over the weekend due to some CI error, but it should get in soon
