### ISSUE TITLE
Reference Manual code throws `TypeError`  in 22.1.0-dev and 21.3.0

### ISSUE THREAD

**Issue by Galunid** [oracle/graalpython#246]
Taken from [Reference Manual](https://www.graalvm.org/reference-manual/python/Interoperability/)
```python
import java
BigInteger = java.type("java.math.BigInteger")
myBigInt = BigInteger(42)
myBigInt.shiftLeft(128)
# public Java methods can just be called
myBigInt["not"]()
# Java method names that are keywords in Python can be accessed using "[]"
byteArray = myBigInt.toByteArray()
# Java arrays can act like Python lists
print(list(byteArray))
```

Throws the following error:
```
Traceback (most recent call last):
  File "/mnt/newDockerfile/pyexec.py", line 7, in <module 'pyexec.py'>
    myBigInt = BigInteger(42)
TypeError: invalid instantiation of foreign object
```

GraalPython: `GraalVM Python 3.8.5 (GraalVM CE Native 22.1.0-dev)`/`Python 3.8.5 (GraalVM CE Native 21.3.0)`

**Comment by Galunid** [comment]
The first issue can actually be solved by changing
```java
myBigInt = BigInteger(42)
```

to
```java
myBigInt = BigInteger("42") // int -> String
```

This results in a different error though
```
Traceback (most recent call last):
  File "/app/pyexec.py", line 6, in <module 'pyexec.py'>
    myBigInt["not"]()
TypeError: 'foreign' object is not subscriptable
```

You can't call this method as `.not()`

**Comment by msimacek** [comment]
Thank you for the report. I fixed the example to use `BigInteger.valueOf` and `getattr` (instead of `[]`)

**Comment by msimacek** [comment]
It might take a while to propagate to the main webpage. You can see the fixed version here: https://github.com/oracle/graalpython/blob/master/docs/user/Interoperability.md
