### ISSUE TITLE
Not able to detect null returned from java code

### ISSUE THREAD

**Issue by stalv** [oracle/graalpython#256]
I'm facing with the issue when I'm unable to do null check after calling some java methods on python side. Obvious attempt to check it like `java_result is not None` doesn't work as it returns an object of 'foreign' type.  If I do `str(java_result)` it returns `None` which is a bit misleading. I was assuming that it would be treated as python's NoneType like it would be treating string object returned from java method as python's str type. Do I miss something or there is no way at the moment to do a null check on the python side?

MRE for running in graal python REPL (`graalpython --jvm`):
```
Python 3.8.5 (Wed Dec 29 11:21:19 CET 2021)
[Graal, GraalVM CE, Java 11.0.13] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import java.util.HashMap
>>> map = java.util.HashMap()
>>> test = map.put(1, "test")
>>> test2 = map.put(1, "test2")
>>> type(test)
<class 'foreign'>
>>> type(test2)
<class 'str'>
>>> test
None
>>> test2
'test'
>>> test is None
False
```

**Comment by msimacek** [comment]
Hi @stalv, Java `null` is a different object from `None` so it doesn't compare with `is`. You can do the null check with `==`, i.e. `test == None`. The reason why we don't convert `null` to `None` is that the interop API is also used for JavaScript interop and JavaScript has two null values - `null` and `undefined` and we need to be able to keep the distinction.

**Comment by stalv** [comment]
Hi @msimacek, thanks for the hint with `==`, that works perfect.
