### ISSUE TITLE
Python collections are not iterable as Java Collections

### ISSUE THREAD

**Issue by wdobler** [oracle/graalpython#260]
In graal-22.0.0.2, there is some mismatch between Python collection types and
Java `Collection`s and `Iterable`s.

A Java method that expects a `Collection` argument cannot iterate over that
argument when it is a Python `list` or `set`.
A Java method that expects an `Iterable` works fine:

~~~python
from java.org.wd import Log4JConfigurator

from typing import List, Set

loggers_list: List[str] = ["stdout", "file"]
loggers_set: Set[str] = set(loggers_list)


# Works: Python list as Java List
Log4JConfigurator.setupLoggingList(loggers_list)

# Unsupported operation identifier 'iterator' and  object '{'stdout',
# 'file'}'(language: Python, type: set). Identifier is not executable or
# instantiable:
# Log4JConfigurator.setupLoggingSet(loggers_set)

# Unsupported operation identifier 'iterator' and  object '['stdout',
# 'file']'(language: Python, type: list). Identifier is not executable or
# instantiable:
# Log4JConfigurator.setupLoggingCollection(loggers_list)

# Unsupported operation identifier 'iterator' and  object '{'stdout',
# 'file'}'(language: Python, type: set). Identifier is not executable or
# instantiable:
# Log4JConfigurator.setupLoggingCollection(loggers_set)

# These work, too: Python list or set as Java Iterable:
Log4JConfigurator.setupLoggingIterable(loggers_list)
Log4JConfigurator.setupLoggingIterable(loggers_set)
~~~

~~~java
package org.wd;

import java.util.Collection;
import java.util.List;
import java.util.Set;

public class Log4JConfigurator {

    public static void setupLoggingSet(Set<String> loggerNames) {
        System.out.println("setupLoggingSet:");
        for (String logger : loggerNames) {
            System.out.println("  " + logger);
        }
    }

    public static void setupLoggingList(List<String> loggerNames) {
        System.out.println("setupLoggingList:");
        for (String logger : loggerNames) {
            System.out.println("  " + logger);
        }
    }

    public static void setupLoggingCollection(Collection<String> loggerNames) {
        System.out.println("setupLoggingCollection:");
        for (String logger : loggerNames) {
            System.out.println("  " + logger);
        }
    }

    public static void setupLoggingIterable(Iterable<String> loggerNames) {
        System.out.println("setupLoggingIterable:");
        for (String logger : loggerNames) {
            System.out.println("  " + logger);
        }
    }
}
~~~

Given that `Collection<T>` implements `Iterable<T>`, iterating over arbitrary
Collections should be possible.

**Comment by msimacek** [comment]
Hi @wdobler, thank you for your interest in graalpython. It should indeed be possible to pass python collections to methods taking `Collection` and `Set`. The wrappers that make the mapping from Java to python objects are not part of graalpython, but they are provided by the Truffle framework we use for implementing interoperability. I created a request for the Truffle team to add the missing wrappers.

**Comment by wdobler** [comment]
Thanks for the clarification.

If there is anything I can do myself, I'd be interested to know. Like
- open an issue on the Truffle issue tracker (where would that be?)
- playing with the Truffle source code myself (but I would need a pointer to know where to start)

**Comment by msimacek** [comment]
Truffle added support for mapping `Collection` as part of oracle/graal@2c17ca6c219ec1a5966f2c54f238d8cd395a42e7. However, there will be no support for `Set` since there is not interop set API, so there would be no way to map other operations than iteration.

**Comment by rubyFeedback** [comment]
So I read about this just now due to the blog news here:

https://medium.com/graalvm/whats-new-in-truffle-and-graal-languages-40027a59c401

For instance:

"Improved Array Access. We added the ability to use Value#as(Collection.class) to map guest language arrays (Value#hasArrayElements()) to the Java Collection interface"

GraalVM has very helpful and useful documentation available at:

https://www.graalvm.org/latest/docs/

Do the docs also include one or two example in how to use that specifically? That is the (Value#hasArrayElements()).

I am just asking in the event no example covers that yet; if it is covered then please disregard my question here.

**Comment by msimacek** [comment]
@rubyFeedback Truffle's javadoc documents the [`Value#as(Class)` method](https://www.graalvm.org/truffle/javadoc/org/graalvm/polyglot/Value.html#as-java.lang.Class-). There is an example for `List`. `Collection` should work the same.
