### ISSUE TITLE
invoke java method

### ISSUE THREAD

**Issue by yuanChina** [oracle/graalpython#264]
I use java for host language  and  then create a python class impletement java interface . when then python method invoke java method I got an PolyglotException,  Here are the details

org.graalvm.polyglot.PolyglotException: TypeError: no applicable overload found (overloads: [Method[public xxx.buy(java.lang.Double,java.lang.Double)], Method[public xxx.Order xxx.buy(Symbol,java.lang.Double,java.lang.Double)]], arguments: [0.0 (Double), PythonAbstractNativeObject(0x7fac146864c8) (PythonAbstractNativeObject)])
	at <python>.onBar(test:100) ~[?:?]
	at com.oracle.truffle.polyglot.PolyglotObjectProxyHandler.invoke(PolyglotObjectProxyHandler.java:103) ~[org.graalvm.truffle:?]

that I invoke by  context.buy(0.0, abs(buy_ratio) * total_amount)
 the type of  buy_ratio  is float and the type of  total_amount  is numpy.float64

Please give me some advice . thanks

**Comment by msimacek** [comment]
Hi, @yuanChina, there's no implicit conversion from `numpy.float64` to a java double. You need to convert it explicitly, like this:
```python
context.buy(0.0, float(abs(buy_ratio) * total_amount))
```

**Comment by yuanChina** [comment]
ok ，but  doesn't the plugin plan to convert automatically？ @msimacek

**Comment by msimacek** [comment]
No, there are technical problems in doing that. First, python objects are often convertible to multiple types and Java allows multiple overloaded methods with the same name taking different types - it wouldn't know which one to pick. Second, for integer types, we don't know if the objects are convertible without running the conversion function, which would be bad for performance and could have side-effects.
