### ISSUE TITLE
is it possible to use graalpython like graaljs?

### ISSUE THREAD

**Issue by tellmewhattodo** [oracle/graalpython#270]
I'am interested in using python via polyglot API, but there's no document about that, is it not supported? 
when will there be polyglot Context support

**Comment by msimacek** [comment]
Hi @tellmewhattodo. It's documented [here](https://www.graalvm.org/22.1/reference-manual/embed-languages/). The examples in the manual show JS by default, but can be switched to python. The grey header above each example has different tabs for different languages.
