### ISSUE TITLE
Getting LLVMPolyglotException when import numpy

### ISSUE THREAD

**Issue by limanhei** [oracle/graalpython#272]
I am trying to run python from Java/Kotlin. The python script worked correctly when running on graalpython in command prompt. However, when I Run inside Java/Kotlin, it throws LLVMPolyglotException: Cannot read from index 0 of polyglot value. In my python file I didn't do anything except import numpy, didn't actually used the lib.

My apologies for doing screenshot instead of putting the codes here.

![16570894216253944397048163920640](https://user-images.githubusercontent.com/4110588/177485233-fd4912b3-bba1-40fb-aae9-32d114bfa535.jpg)
![16570895315252920847721682817699](https://user-images.githubusercontent.com/4110588/177485292-e79ec9a3-6e26-4479-93f5-cff5985f7883.jpg)
![16570895752528622391312831906987](https://user-images.githubusercontent.com/4110588/177485414-1fc3056b-5737-4e27-b3e5-6272b1a2601b.jpg)

**Comment by msimacek** [comment]
Hi @limanhei, you also need to enable host access with `allowHostAccess(HostAccess.ALL)`.
