### ISSUE TITLE
Sulong benchmark?

### ISSUE THREAD

**Issue by chadbrewbaker** [oracle/graalpython#274]
Ed Kmett introduced me to the GraalVM Sulong project to run LLVM bytecode.

Is it totally insane to compile CPython to LLVM bytecode then run it in GraalVM and benchmark against this project?

 @chrisseaton - ditto for Truffle Ruby - running CRuby under Sulong?

**Comment by chrisseaton** [comment]
CRuby has support for compiling to WASM - maybe that configuration would be a place to start (as I guess it's more well behaved?).
