### ISSUE TITLE
Python "==" returns false for Java strings

### ISSUE THREAD

**Issue by kfirt** [oracle/graalpython#293]
Seems like there is a regression in 22.3.0 when using java Maps.
Using the code below 

- with 22.2.0 returns `True` for both `mymap['source'] == 'foo'` and `mymap.get('source') == 'foo'`
- with 22.3.0 returns `False` for `mymap['source'] == 'foo'` and `True` for `mymap.get('source') == 'foo'`

```
    public static void main(String[] args) {
        Context ctx = Context.newBuilder().allowAllAccess(true).build();
        String workflowScript = """
                def enrich(mymap):
                    print(type(mymap))
                    print(mymap['source'] == 'foo')
                    print(mymap.get('source') == 'foo')
                """;


        ctx.eval("python", workflowScript);
        Map source = Map.of("source", "foo");
        ctx.getBindings("python").getMember("enrich").execute(source);
    }
```

If you could also remove the assertions from `com.oracle.graal.python.nodes.truffle.TruffleStringMigrationHelpers` it will ease running JUnit tests on our end

**Comment by timfel** [comment]
The fix for this is now on master, and will be released with 23.0.0 in January. The reproducer you have provided was added to our test suite so we won't regress on this again. Thank you for your help in tracking this down!
