### ISSUE TITLE
bad patch for MarkupSafe

### ISSUE THREAD

**Issue by The-Alchemist** [oracle/graalpython#315]
```
Patching package MarkupSafe using /Library/Java/JavaVirtualMachines/graalvm-ce-java19-22.3.1/Contents/Home/languages/python/lib-graalpython/patches/MarkupSafe/sdist/MarkupSafe.patch
patching file setup.py
Hunk #1 FAILED at 52.
1 out of 1 hunk FAILED -- saving rejects to file setup.py.rej
```

I'd send a PR but I can't find the source for `MarkupSafe.patch`. :(  Is there a git repo for these patches?  Had trouble finding it.

Actually, the patch is no longer necessary, as it seems to be merged already.

## Patch contents

```

-supports_speedups = platform.python_implementation() not in {"PyPy", "Jython"}
+supports_speedups = platform.python_implementation() not in {"PyPy", "Jython", "GraalVM"}`
```

## source setup.py

https://github.com/pallets/markupsafe/blob/main/setup.py

**Comment by msimacek** [comment]
You're right, it's been upstreamed. I'll remove it

**Comment by msimacek** [comment]
Ah, somebody removed it in master already, that's why you couldn't find it. It won't be there in the next release
