### ISSUE TITLE
SEGFAULT when doing `from cryptography.hazmat.bindings.openssl import binding` (with cryptography 3.4.7)

### ISSUE THREAD

**Issue by jiridanek** [oracle/graalpython#329]
* I'm aware I need to build cryptography with an older OpenSSL due to https://github.com/oracle/graalpython/issues/267

* followup to https://github.com/oracle/graalpython/issues/325, I can now install the package, but I cannot import it

I tried several ways to build with openssl 1.1.1, but every which way, I get a VM segfault when I import the built library

Is there something I can do to further debug the crash? Should I (somehow) try to build openssl for GraalVM myself, instead of linking to native shared library?

```
$ env CFLAGS="-I/nix/store/syx9zczfg4p6x013lyg4j6nr1fqj4l9m-openssl-1.1.1l-dev/include" LDFLAGS="-L/nix/store/hl09r5178s52savxh4pmkg86jjlakd4p-openssl-1.1.1l/lib" venvgpy_nightly/bin/graalpy -m pip install -U cryptography --force-reinstall --no-binary cryptography
$ LD_LIBRARY_PATH=/nix/store/hl09r5178s52savxh4pmkg86jjlakd4p-openssl-1.1.1l/lib venvgpy_nightly/bin/graalpy -c 'from cryptography.hazmat.bindings.openssl import binding'
```

[stacktrace.txt](https://github.com/oracle/graalpython/files/11112928/stacktrace.txt)

**Comment by msimacek** [comment]
I can reproduce it. It seems it's failing in a call to a native function from the `cffi` module. I'll have a look.

**Comment by jiridanek** [comment]
Now I got the following. I am not sure if it counts as success, yet.

```
$ LD_LIBRARY_PATH=/nix/store/hl09r5178s52savxh4pmkg86jjlakd4p-openssl-1.1.1l/lib venvgpy_nightly/bin/graalpy -c 'from cryptography.hazmat.bindings.openssl import binding'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jdanek/venvgpy_nightly/lib/python3.10/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 172, in <module>
    Binding.init_static_locks()
  File "/home/jdanek/venvgpy_nightly/lib/python3.10/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 146, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/home/jdanek/venvgpy_nightly/lib/python3.10/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 136, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "/home/jdanek/venvgpy_nightly/lib/python3.10/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 102, in build_conditional_library
    setattr(conditional_lib, attr, getattr(lib, attr))
NotImplementedError: op=15
```

**Comment by jiridanek** [comment]
yes, paramiko library now works, when installed like this

```
venvgpy_nightly/bin/graalpy -m pip install paramiko 'bcrypt<4'
```

**Comment by msimacek** [comment]
Hmm, I can import it fine. Since the fix was about updating a patch for `cffi`, could you please try reinstalling `cffi` with `--no-cache-dir` option? It's possible that it's picking up the broken wheel from the cache.
