### ISSUE TITLE
urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with GraalVM

### ISSUE THREAD

**Issue by subashatreya** [oracle/graalpython#335]
Requests module does not currently work with 22.3.1. I get the following error:

"ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with GraalVM JSSE. See: https://github.com/urllib3/urllib3/issues/2168"

venv$ pip list
Package            Version
------------------ --------
certifi            2023.5.7
charset-normalizer 3.1.0
hpy                0.0.4
idna               3.4
numpy              1.16.4
pandas             0.25.0
pandas-ta          0.3.14b0
pip                20.1.1
python-dateutil    2.8.2
pytz               2023.3
requests           2.30.0
setuptools         47.1.0
six                1.16.0

**Comment by msimacek** [comment]
I fixed this by adding a patch for urllib3 that disables the check. You may need to reinstall urllib3 in existing environments to take effect.
