### ISSUE TITLE
GraalPy and aalib

### ISSUE THREAD

**Issue by alienhunter3010** [oracle/graalpython#338]
I was writing an experimental repository to promote GraalVM/GraalPy on my company.

I would like to create a Java interface's implementation in Python. To justify this I would like to use `python-aalib` package.

But it raises a `NotImplementedError: Storage is not implemented.`.

I have isolated the problem creating a `venv` w/ graalpy (graalvm-ce-java17-22.3.1), installing packages inside using `pip` and running a REPL python prompt. The error persists:

```
Python 3.8.5 (Thu Jan 19 19:19:43 UTC 2023)
[Graal, GraalVM CE, Java 17.0.6] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import aalib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[OMISSIS]/py-aalib/gvenv/lib/python3.8/site-packages/aalib.py", line 66, in <module>
    DEFAULT_HARDWARE_SETTINGS = HardwareSettings.in_dll(libaa, 'aa_defparams')
NotImplementedError: Storage is not implemented.
```

Is the Storage implementation scheduled, yet?

**Comment by msimacek** [comment]
Hi @alienhunter3010, the storage is already implemented in our master branch. Could you please try a snapshot build from https://github.com/graalvm/graalvm-ce-dev-builds/releases/?
