### ISSUE TITLE
GraalPy bundling instructions in blog post seem to be incorrect

### ISSUE THREAD

**Issue by mikehearn** [oracle/graalpython#339]
https://medium.com/graalvm/whats-new-in-graalvm-languages-161527df3d76

says to use this command

```
graalpy -m standalone binary - module my_script.py - output my_binary
```

but it seems the right command is actually the more expected form

```
graalpy -m standalone binary --module hello.py -o hello
```

**Comment by msimacek** [comment]
Thank you for noticing. It seems that the publishing tool converted every `--` to ` -`. Should be fixed now.
