### ISSUE TITLE
24.1.0 and 24.0.0 releases?

### ISSUE THREAD

**Issue by fakeNews-jpg** [oracle/graalpython#372]
Hello,

In changelog, we see the versions 24.1.0 & 24.0.0, with some interessants changes.

But i can't find them in releases, 

Is it possible to add them in https://github.com/oracle/graalpython/releases/ ?

Thanks a lot in advance,

F.N.

**Comment by msimacek** [comment]
Hi @fakeNews-jpg, those changelog entries are for not yet released versions.

24.0.0 is scheduled to be released on March 19th. 24.1.0 is scheduled for September 17th.

If you want to test unreleased features, you can use snapshot builds from https://github.com/graalvm/graalvm-ce-dev-builds/releases/. They are supposed to be done daily, but for some reason, it seems currently stuck at December 9th. I'll ask our release engineering to fix that.

**Comment by fakeNews-jpg** [comment]
Thanks a lot @msimacek for your answer! i will test the unreleased features with snapshot builds then :)
