### ISSUE TITLE
Exception using Graalpy with JSR223: java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by fit2-zhao** [oracle/graalpython#375]
Run the following JSR223 script :

`from urllib import request`

If you execute the loop, you will find that the heap memory continues to grow.

![image](https://github.com/oracle/graalpython/assets/70558837/b1e45732-2375-4d61-aab3-5258cf86faee)

![image](https://github.com/oracle/graalpython/assets/70558837/e022a464-150b-437c-aa81-87fd4b8fbad8)

**Comment by msimacek** [comment]
Hi @fit2-zhao, I tried running the import in a loop in new contexts and I couldn't reproduce running out of memory. Could you please post your Java code?

**Comment by fit2-zhao** [comment]
Thank you for your reply. I have found the problem and it is the problem I am using.
