### ISSUE TITLE
uv support

### ISSUE THREAD

**Issue by theLastOfCats** [oracle/graalpython#399]
At the moment, graalpy doesn't support uv (blazing fast pypi resolver).

When using it returns strange error:

```bash
(.venv) shaziganshin@box test % uv pip install blacksheep
error: Unknown implementation: `graalpy`
```

**Comment by msimacek** [comment]
Our pip is modified to apply graalpy-specific changes to packages it installs, `uv` would be missing that logic. It's not feasible for us to support alternative package installers. Please use the pip we ship.
