### ISSUE TITLE
Unable to create `GraalPyResources` with shared/predefined engine

### ISSUE THREAD

**Issue by jord1e** [oracle/graalpython#432]
You currently cannot create a `Context` using `GraalPyResources` with a shared engine (`GraalPyResources#createContextBuilder()` followed by `Context.Builder#engine(Engine)`)

This is because `GraalPyResources#createContextBuilder()` sets the `engine.WarnInterpreterOnly` option implicitly. This is not allowed when using a shared engine (which requires `engine.*` options to be set on the Engine alone)

It throws an error either when building the context or when first evaluating (sorry, forgot which one)

![grafik](https://github.com/user-attachments/assets/e6b45879-b0e7-451c-aefe-50211d0d9caf)

I see two resolution paths:
1. Add a `public static Context.Builder contextBuilder(Engine.Builder engineBuilder) { ... }` method to create a builder with an engine and set the `engine.WarnInterpreterOnly` implictely (or a variation of this idea) 
2. If the option is set on the shared engine and has the same value as the Context's option value, do not throw an error (probably preferred)

Options like allowExperimentalOptions set on the shared engine are also overridden by createContextBuilder, but you can work around that by just doing allowExperimentalOptions(true), so not a big problem overall

**Comment by msimacek** [comment]
Hi. This is already fixed on master in 4956b4759d. Unfortunately, we noticed this too late and the fix didn't make it to the release. It should be available in the next release.

**Comment by jord1e** [comment]
Thanks! I'll close it

Maybe still a (good?) idea to look at
> If the option is set on the shared engine and has the same value as the Context's option value, do not throw an error (probably preferred)
