### ISSUE TITLE
Meson failure installing numpy with graalpy-maven-plugin

### ISSUE THREAD

**Issue by zenbones** [oracle/graalpython#434]
On windows 11, using the graalpy-maven-plugin...

`
          <plugin>
            <groupId>org.graalvm.python</groupId>
            <artifactId>graalpy-maven-plugin</artifactId>
            <executions>
              <execution>
                <configuration>
                  <packages>
                    <package>numpy</package>
                  </packages>
                  <pythonHome>
                    <excludes>
                      <exclude>.*</exclude>
                    </excludes>
                  </pythonHome>
                  <pythonResourcesDirectory>${project.basedir}/python-resources</pythonResourcesDirectory>
                </configuration>
                <goals>
                  <goal>process-graalpy-resources</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
`

...yields this error from Meson...

`Collecting numpy
  Downloading numpy-2.0.2.tar.gz (18.9 MB)
     ---------------------------------------- 18.9/18.9 MB 3.1 MB/s eta 0:00:00
auto-patching C API usages in C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\numpy\_core\include\numpy\ndarrayobject.h
auto-patching C API usages in C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\numpy\_core\include\numpy\npy_3kcompat.h
auto-patching C API usages in C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\numpy\_core\src\multiarray\compiled_base.c
auto-patching C API usages in C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\numpy\_core\src\multiarray\dlpack.c
auto-patching C API usages in C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\numpy\_core\src\multiarray\dtype_transfer.c
auto-patching C API usages in C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\numpy\_core\src\multiarray\methods.c
auto-patching C API usages in C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\numpy\_core\src\multiarray\stringdtype\dtype.c
auto-patching C API usages in C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\numpy\_core\src\umath\override.c
auto-patching C API usages in C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\numpy\_core\src\umath\_rational_tests.c
Looking for GraalPy patches for numpy
Patching package numpy using C:\Users\david\AppData\Local\org.graalvm.polyglot\python\python-home\7f99e649dc51b21db2b83ce56bc9742eefe66415\lib-graalpython\patches\numpy\numpy-2.0.0.patch
WARNING: GraalPy needs the 'patch' utility to apply compatibility patches. Please install it using your system's package manager.
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): still running...
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  ? Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 2
  ?─> [56 lines of output]
      + C:\Users\david\Documents\Nutshell\empyrean\aeon\pantheon\com\forio\epicenter\grid\worker\python-resources\venv\Scripts\graalpy.exe C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\vendored-meson\meson\meson.py setup C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\.mesonpy-46jrmj2j -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\.mesonpy-46jrmj2j\meson-python-native-file.ini
      The Meson build system
      Version: 1.4.99
      Source dir: C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b
      Build dir: C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\.mesonpy-46jrmj2j
      Build type: native build
      Project name: NumPy
      Project version: 2.0.2
      Traceback (most recent call last):
        File "C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\vendored-meson\meson\mesonbuild\mesonmain.py", line 188, in run
          return options.run_func(options)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\vendored-meson\meson\mesonbuild\msetup.py", line 363, in run
          app.generate()
        File "C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\vendored-meson\meson\mesonbuild\msetup.py", line 187, in generate
          return self._generate(env, capture, vslite_ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\vendored-meson\meson\mesonbuild\msetup.py", line 209, in _generate
          intr = interpreter.Interpreter(b, user_defined_options=user_defined_options)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\vendored-meson\meson\mesonbuild\interpreter\interpreter.py", line 320, in __init__
          self.parse_project()
        File "C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 129, in parse_project
          self.evaluate_codeblock(self.ast, end=1)
        File "C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 195, in evaluate_codeblock
          raise e
        File "C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 187, in evaluate_codeblock
          self.evaluate_statement(cur)
        File "C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 201, in evaluate_statement
          return self.function_call(cur)
                 ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 528, in function_call
          res = func(node, func_args, kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 250, in wrapper
          return f(*nargs, **wrapped_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 569, in wrapper
          return f(*wrapped_args, **wrapped_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\vendored-meson\meson\mesonbuild\interpreter\interpreter.py", line 1308, in func_project
          mesonlib.setup_vsenv(force_vsenv)
        File "C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\vendored-meson\meson\mesonbuild\utils\vsenv.py", line 121, in setup_vsenv
          return _setup_vsenv(force)
                 ^^^^^^^^^^^^^^^^^^^
        File "C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\vendored-meson\meson\mesonbuild\utils\vsenv.py", line 78, in _setup_vsenv
          if windows_detect_native_arch() == 'arm64':
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\david\AppData\Local\Temp\pip-install-_qpjhkgz\numpy_cca38dee130b41b0884b1cf835bfb30b\vendored-meson\meson\mesonbuild\utils\universal.py", line 736, in windows_detect_native_arch
          process = ctypes.c_void_p(kernel32.GetCurrentProcess())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      OverflowError: can't convert negative value to unsigned int

      ..\meson.build:1:0: ERROR: Unhandled python exception

          This is a Meson bug and should be reported!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

? Encountered error while generating package metadata.
?─> See above for output.`

**Comment by msimacek** [comment]
Hi, @zenbones, you need to install the `patch` utility so that pip can apply patches to add compatibility fixes. It says that in the output:
```
WARNING: GraalPy needs the 'patch' utility to apply compatibility patches. Please install it using your system's package manager.
```
Sorry that it's not more visible, in the next release it should be printed in color. Maybe we should make it hard error instead.

**Comment by zenbones** [comment]
Thanks. A few comments.

1) It's a warning, which generally means the process can work around his on its own, so yes, an error might be better.
2) The warning (or error) assumes I know what the 'patch' utility is, or how to install it properly. Maybe adding the shell (or other) installation instructions would help others in the same situation. This is not a utility I've ever had to deal with before in either Python or Java.

So... what's the patch utility (which I'm about to ask my web search client)?

**Comment by zenbones** [comment]
Having looked up the patch utility, the AI generated 'answer' is 'apt install patch' or 'brew install patch'... oh, hey, I'm on a windows system. Trying to find the equivalent, but, you know, any help appreciated.

**Comment by msimacek** [comment]
True, on Linux it's something that you typically already have and on Mac it's easy to install. This patching logic was added way before we had any windows support and we didn't properly re-evaluate it for windows. The patch tool should be available as a part of [Git for Windows], but we need to look at how to make it available so that the maven plugin would pick it up. We're also working on building the numpy wheel for windows, so you wouldn't have to do any of this.

**Comment by timfel** [comment]
FYI, I used the one from [gnuwin32](https://gnuwin32.sourceforge.net/packages/patch.htm) on my machine

**Comment by timfel** [comment]
Note that this is the setup I have:

1. Install (at least) Visual Studio 2022 Build Tools (e.g. `winget install Microsoft.VisualStudio.2022.BuildTools` on a recent Win11)
2. Get [patch.exe](https://gnuwin32.sourceforge.net/packages/patch.htm) and put it somewhere you'll find it again, in a path *without spaces*
3. Start a "Developer PowerShell for VS 2022"
4. Put patch.exe on the PATH (e.g. "$Env:PATH+=";c:\my\full\path\to\the\folder\that\containes\patchexe\"
5. Now use this prompt to make your graalpy venv and install packages

**Comment by zenbones** [comment]
What I actually need is for the given instructions to work on a windows machine for Java, Maven and IntelliJ. And the IDE should not matter. The write once run anywhere (supported) should support windows. I'm happy to put the patch executable on my path, if someone will tell me where the patch executable resides. I have Git installed via chocolatey if that helps. Again, I think that should not matter. But it's not like this process will actually run on windows. Windows is my development environment. Ubuntu is the production environment. And nothing else in our whole Java-based stack cares. We have maybe 10 lines of code that check for  a windows environment and does something slightly accommodating, and only because of file locking in the windows file system.

I think this is a problem. I think it's going to be a problem until it has a uniform resolution that hides any os specific implementation details. Given the current instructions don't work, I'd call this a bug. Should I file a new ticket as a bug?

**Comment by timfel** [comment]
@zenbones We are in complete agreement about the ideal state of things 🙂 We are working towards that ideal state, but it's a long road. The Python ecosystem does not hide platform details, a lot of the packages are native code and most development in both the core libraries as well as the ecosystem is Unix-centric. We will continue to work on hiding those details, but it is a large and multi-faceted effort.

**Comment by zenbones** [comment]
I get it. I'm grateful for the effort. I guess wat you're saying is that anything I might place in a bug ticket for is already on the roadmap. You are probably already very aware of https://www.lfd.uci.edu/~gohlke/pythonlibs/, which seems to have been removed, which is a shame, because Mr. Gohlke's windows builds worked. I don't know if any of his work would be useful in getting windows ports running, but I guess you could ask him.

I need a handful of python packages. Is there any set of instructions for ubuntu/windows that would provide useable, automatable steps for setting up six, jsonpickle, numpy, scipy, chainmap, or the like?

**Comment by timfel** [comment]
> I need a handful of python packages. Is there any set of instructions for ubuntu/windows that would provide useable, automatable steps for setting up six, jsonpickle, numpy, scipy, chainmap, or the like?

The best in terms of automation is the GitHub action workflow I linked a above. It's a simple python script, but you'll have to figure out yourself how to get build dependencies like Fortran into the build system

**Comment by msimacek** [comment]
> Below you find the output. Any idea how to fix it?

I haven't seen this one yet, I need to try if I can reproduce it in a VM. But still, there is a warning that it couldn't find the patch tool. It needs to be on `PATH` for the build to find it.

> I'll try the GitHub action workflow. If this works, what's the best way to integrate the wheel in the maven build process?

You can put the path to the wheel as a dependency in the `<package>` tag
