### ISSUE TITLE
Support for pydantic-core 2.20

### ISSUE THREAD

**Issue by ampdot-io** [oracle/graalpython#451]
Hi,

My application depends on Pydantic 2.7's support for the generic `Secret` type, which I use to hide sensitive information from telemetry and logging.

GraalPython currently only supports `pydantic-core==2.10.1`, which corresponds to Pydantic 2.4, while I need patches for pydantic-core of at least 2.20.

Is there any tool for generating candidate updated patches automatically, or any proposal for a system that allows library upgrades more easily than the current system?

**Comment by ampdot-io** [comment]
Oh, it seems like Pydantic v2 isn't supported? My application has a hard dependency on pydantic v2

**Comment by msimacek** [comment]
Hi @ampdot-io, I'll a new patch.

> Is there any tool for generating candidate updated patches automatically, or any proposal for a system that allows library upgrades more easily than the current system?

There's a already an autopatching system that applies common changes for things that can be done automatically. The patch files are for the things that the automated tool didn't handle. When we have a reasonable confidence a patch will apply on new releases, we don't pin it to specific versions so it will try to apply it on new releases as they are made. But in case of `pydantic-core`, we know that the patch won't apply to newer releases and will need some additional human work to be adapted to the new version, so we pin it. We already upstreamed GraalPy support in PyO3, the framework that `pydantic-core` is built upon and recently we upstreamed GraalPy support in `jiter` which another `pydantic-core` dependency. We're going to upstream the patch for `pydantic-core` itself soon and then no patch will be needed anymore.

**Comment by ampdot-io** [comment]
Thanks!

**Comment by ampdot-io** [comment]
Hi,

Please let me know when this is completed. I can't remove my application's dependency on this version of Pydantic.

**Comment by msimacek** [comment]
The PR is merged, new snapshot build should be available at https://github.com/graalvm/graal-languages-ea-builds next week
