### ISSUE TITLE
How to install torch using graalvm24.1.1 in wsl2 ubuntu 

### ISSUE THREAD

**Issue by yan-zhi-cheng** [oracle/graalpython#452]
I tried many times but kept getting errors,
is there a successful demo or Linux command?

**Comment by msimacek** [comment]
Hi @yan-zhi-cheng, there shouldn't be anything special, except you need to install some development dependencies in your system. We have some scripts for building wheels in https://github.com/oracle/graalpython/blob/master/scripts/wheelbuilder/README.md.

**Comment by yan-zhi-cheng** [comment]
@msimacek 
<img width="912" alt="image" src="https://github.com/user-attachments/assets/de03a884-fd61-4807-8806-b1e8a8ba38b7">
Thank you for your reply. I have now executed the task you mentioned. How long will it take? I chose to build all packages by default.

**Comment by yan-zhi-cheng** [comment]
Thanks again, the execution has been completed. Next, I will test it.
