### ISSUE TITLE
build-linux-amd64-wheels.yml fails on actions

### ISSUE THREAD

**Issue by yan-zhi-cheng** [oracle/graalpython#453]
build-windows-amd64-wheels.yml is executed successfully, but the progress of build-linux-amd64-wheels is stuck in the screenshot
<img width="945" alt="image" src="https://github.com/user-attachments/assets/699e5f25-9a30-4207-adbd-476ffd310f00">

**Comment by timfel** [comment]
Ah, yes, the `runs-on` is wrong in yml, thanks for the catch. Should just be `ubuntu-latest`. I'll open a PR to fix it

**Comment by yan-zhi-cheng** [comment]
@timfel I think it is not enough to just modify runs-on in the configuration. I have tried to modify it myself, and it reports some container-related errors.
In addition, if I want to get the torch package, is it enough to just add torch==2.2.1 in package.txt?

**Comment by yan-zhi-cheng** [comment]
![image](https://github.com/user-attachments/assets/dfa43118-7d0c-4646-92ed-44793687befe)
I changed the packages.txt to torch==2.2.1. Now I get an error during the build process under Windows.

**Comment by yan-zhi-cheng** [comment]
@timfel That's fine, I'm just interested in testing it, but the build on Linux did not succeed. Should I choose version 1.13.1?
**
![image](https://github.com/user-attachments/assets/9795b7a1-b2c3-4467-ae33-454bf9f024a0)
**

**Comment by timfel** [comment]
@yan-zhi-cheng you can omit the version and it'll pick the best supported one
