### ISSUE TITLE
jiter doesn't build on windows

### ISSUE THREAD

**Issue by Jhgomez** [oracle/graalpython#456]
# Description
I'm compiling and running this [sample app](https://github.com/graalvm/graal-languages-demos/tree/main/graalpy/graalpy-openai-starter) in Windows 11, I'm also making sure I have installed all the requirements indicated in [this guide](https://github.com/graalvm/graal-languages-demos/blob/main/graalpy/graalpy-native-extensions-guide/README.md). I have two setups, in my first setup I have installed Ubuntu 24.04.1 LTS using WSL 2, I have installed GraalVm 23 using SDKMAN and installed GCC and it compiles. In my second set up I want to run it entirely in Windows 11, so I downloaded GraalVm 23 and set JAVA_HOME, and downloaded GCC using [Cygwin](https://cygwin.com/) but when I run `./mvnw package`, I get the following error:

[error.txt](https://github.com/user-attachments/files/17908921/error.txt)

It failed building Wheel for jiter and pydantic_core. Can you help me understand what I'm I doing wrong?

This is the info I get when I print the versions:

* java --version = java 23.0.1 2024-10-15 
* gcc --version = gcc (GCC) 12.4.0
* cargo --version = cargo 1.82.0 (8f40fc59f 2024-08-21)

**Comment by msimacek** [comment]
Hi @Jhgomez, you're not doing anything wrong. I'm sorry, but our windows support is still quite basic and mostly covers just pure python code. We don't test native extensions on windows much yet. `jiter==0.5.0` doesn't compile from source in the current release, on Linux it relies on the prebuilt wheel we provide. The current version `jiter==0.7.1` should be buildable from source, so you can try changing the version in the example. I tried it in a windows VM and it compiled, but then it failed to link the library. We will look into that in the future, but for now, please stay with your WSL 2 setup.

**Comment by Jhgomez** [comment]
Hello @msimacek, thanks for replying. I tried `jiter==0.7.1` and other versions as well and got the error log below ub all the versions. Any suggestions?

[error.txt](https://github.com/user-attachments/files/17939528/error.txt)

**Comment by msimacek** [comment]
That's the same linking error that I got in my VM. It seems it's a bug in the underlying pyo3 framework for rust bindings. I'll try to look into it in the future, but I don't have any workaround as of now.

**Comment by msimacek** [comment]
Should be fixed in the next release.
