### ISSUE TITLE
Setup CI publishing the artifacts built after each commit.

### ISSUE THREAD

**Issue by KOLANICH** [oracle/graalpython#49]
GitLab CI or AppVeyor can be used for that.

**Comment by timfel** [comment]
I don't think we're planning to do this, but @ansalond can probably say more

**Comment by ansalond** [comment]
We would like to start publishing nightly builds, but we do not have an ETA yet.

**Comment by msimacek** [comment]
Oracle GraalPy has snapshot builds here: https://github.com/graalvm/graal-languages-ea-builds/releases
GraalPy Community has them here: https://github.com/graalvm/graalvm-ce-dev-builds/releases/

It's not after every commit, it's after every Graal import (usually happens weekly).
