### ISSUE TITLE
ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by oroppas** [oracle/graalpython#52]
```
>>> import fcntl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "_bootstrap.py", line 1074, in __import__
  File "_bootstrap.py", line 994, in _gcd_import
  File "_bootstrap.py", line 971, in _find_and_load
  File "_bootstrap.py", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fcntl'
```

**Comment by timfel** [comment]
Are there any operations in particular are you interested to use from the `fcntl` module? We are emulating the semantics and thus might not be able to provide all functions and knowing which ones are useful to people may help us focus.

**Comment by oroppas** [comment]
I was testing TextFSM (https://github.com/google/textfsm) and they use fcntl to get terminal size:

```
def TerminalSize():
  """Returns terminal length and width as a tuple."""
  try:
    with open(os.ctermid(), 'r') as tty_instance:
      length_width = struct.unpack(
          'hh', fcntl.ioctl(tty_instance.fileno(), termios.TIOCGWINSZ, '1234'))
  except (IOError, OSError):
    try:
      length_width = (int(os.environ['LINES']),
                      int(os.environ['COLUMNS']))
    except (ValueError, KeyError):
      length_width = (24, 80)
  return length_width
```

**Comment by timfel** [comment]
Thanks. Doing this properly will require some more time. I just tried with an empty fcntl module for now and with a few other small fixes, we pass 84 of the 94 unittests in textfsm master. The fixes should show up some time Friday.

**Comment by oroppas** [comment]
Thank you, @timfel.
I keep this issue opened until remaining fixes come and all the unit tests in textfsm pass.

**Comment by oroppas** [comment]
Closed as all the issues have been resolved.
