### ISSUE TITLE
[inspect] getfile path resolution

### ISSUE THREAD

**Issue by oroppas** [oracle/graalpython#91]
`$ cat test_inspect_getfile.py`

```
import inspect

print( inspect.getfile(inspect.currentframe()) )
```

CPython only prints file name `test_inspect_getfile.py` whereas GraalPython prints
not only the file name but also the full path to the file.

**Comment by timfel** [comment]
I assume that only started recently, because we fixed this: https://github.com/graalvm/graalpython/issues/78

**Comment by fangerer** [comment]
I agree, GraalPython behaves differently because it now always returns the absolute path for a code object. But note that the path CPython returns is also just relative to the current working directory. Do you rely on having source path's relative to CWD?

**Comment by oroppas** [comment]
I adopted the method to import a module from a relative path:

```python
# Import a module from a relative path
# https://stackoverflow.com/questions/279237/import-a-module-from-a-relative-path/6098238

import os, sys, inspect

def set_module_relative_path(subfolder):

  cmd_subfolder = os.path.realpath(os.path.abspath(os.path.join(os.path.split(inspect.getfile( inspect.currentframe() ))[0], subfolder)))

  if cmd_subfolder not in sys.path:
      sys.path.insert(0, cmd_subfolder)
```

so that I can run a quick test without installing module.

**Comment by timfel** [comment]
@oroppas your code snippet will not work if you run the script from a different directory in cpython, either. Also, there is no reason to use the inspect module. This would be better:

```
import os, sys

def set_module_relative_path(subfolder):
  os.path.abspath(os.path.join(os.path.dirname(__file__), subfolder))
  if subfolder not in sys.path:
    sys.path.insert(0, cmd_subfolder)
```

**Comment by oroppas** [comment]
@timfel, thanks for the better code. I always created the symlink so it always worked.
Aside from the necessity of inspect module to achieve what I want to do, is the difference
of the behavior of the inspect module between the implementations considered to be the bug?

**Comment by timfel** [comment]
Yes

**Comment by oroppas** [comment]
Thank you!

**Comment by msimacek** [comment]
From 3.9 on, CPython prints full paths too, so there's no difference in implementations anymore. It's nice that CPython is becoming more compatible with us :laughing:
